// Code generated by protoc-gen-go. DO NOT EDIT.
// source: space.proto

package spacego

import (
	financego "aletheiaware.com/financego"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Delta struct {
	// File Offset.
	Offset uint64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// Number of Bytes Removed.
	Remove uint64 `protobuf:"varint,2,opt,name=remove,proto3" json:"remove,omitempty"`
	// Bytes Added.
	Add                  []byte   `protobuf:"bytes,3,opt,name=add,proto3" json:"add,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Delta) Reset()         { *m = Delta{} }
func (m *Delta) String() string { return proto.CompactTextString(m) }
func (*Delta) ProtoMessage()    {}
func (*Delta) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8a3f24abfdc04ca, []int{0}
}

func (m *Delta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Delta.Unmarshal(m, b)
}
func (m *Delta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Delta.Marshal(b, m, deterministic)
}
func (m *Delta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delta.Merge(m, src)
}
func (m *Delta) XXX_Size() int {
	return xxx_messageInfo_Delta.Size(m)
}
func (m *Delta) XXX_DiscardUnknown() {
	xxx_messageInfo_Delta.DiscardUnknown(m)
}

var xxx_messageInfo_Delta proto.InternalMessageInfo

func (m *Delta) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Delta) GetRemove() uint64 {
	if m != nil {
		return m.Remove
	}
	return 0
}

func (m *Delta) GetAdd() []byte {
	if m != nil {
		return m.Add
	}
	return nil
}

type Meta struct {
	// Name of file.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// MIME type of file.
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Meta) Reset()         { *m = Meta{} }
func (m *Meta) String() string { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()    {}
func (*Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8a3f24abfdc04ca, []int{1}
}

func (m *Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meta.Unmarshal(m, b)
}
func (m *Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meta.Marshal(b, m, deterministic)
}
func (m *Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meta.Merge(m, src)
}
func (m *Meta) XXX_Size() int {
	return xxx_messageInfo_Meta.Size(m)
}
func (m *Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Meta proto.InternalMessageInfo

func (m *Meta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Meta) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Preview struct {
	// MIME type of preview
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Preview data
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Preview width
	Width uint32 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	// Preview height
	Height               uint32   `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Preview) Reset()         { *m = Preview{} }
func (m *Preview) String() string { return proto.CompactTextString(m) }
func (*Preview) ProtoMessage()    {}
func (*Preview) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8a3f24abfdc04ca, []int{2}
}

func (m *Preview) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Preview.Unmarshal(m, b)
}
func (m *Preview) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Preview.Marshal(b, m, deterministic)
}
func (m *Preview) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Preview.Merge(m, src)
}
func (m *Preview) XXX_Size() int {
	return xxx_messageInfo_Preview.Size(m)
}
func (m *Preview) XXX_DiscardUnknown() {
	xxx_messageInfo_Preview.DiscardUnknown(m)
}

var xxx_messageInfo_Preview proto.InternalMessageInfo

func (m *Preview) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Preview) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Preview) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Preview) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type Tag struct {
	// The value of tag applied to meta
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// The reason for tagging
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8a3f24abfdc04ca, []int{3}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Tag) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type Registrar struct {
	Merchant             *financego.Merchant `protobuf:"bytes,1,opt,name=merchant,proto3" json:"merchant,omitempty"`
	Service              *financego.Service  `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Registrar) Reset()         { *m = Registrar{} }
func (m *Registrar) String() string { return proto.CompactTextString(m) }
func (*Registrar) ProtoMessage()    {}
func (*Registrar) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8a3f24abfdc04ca, []int{4}
}

func (m *Registrar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Registrar.Unmarshal(m, b)
}
func (m *Registrar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Registrar.Marshal(b, m, deterministic)
}
func (m *Registrar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Registrar.Merge(m, src)
}
func (m *Registrar) XXX_Size() int {
	return xxx_messageInfo_Registrar.Size(m)
}
func (m *Registrar) XXX_DiscardUnknown() {
	xxx_messageInfo_Registrar.DiscardUnknown(m)
}

var xxx_messageInfo_Registrar proto.InternalMessageInfo

func (m *Registrar) GetMerchant() *financego.Merchant {
	if m != nil {
		return m.Merchant
	}
	return nil
}

func (m *Registrar) GetService() *financego.Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func init() {
	proto.RegisterType((*Delta)(nil), "space.Delta")
	proto.RegisterType((*Meta)(nil), "space.Meta")
	proto.RegisterType((*Preview)(nil), "space.Preview")
	proto.RegisterType((*Tag)(nil), "space.Tag")
	proto.RegisterType((*Registrar)(nil), "space.Registrar")
}

func init() { proto.RegisterFile("space.proto", fileDescriptor_b8a3f24abfdc04ca) }

var fileDescriptor_b8a3f24abfdc04ca = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x91, 0x41, 0x6b, 0xfa, 0x40,
	0x10, 0xc5, 0xc9, 0xdf, 0xa8, 0xff, 0x8c, 0x0a, 0x76, 0x29, 0x12, 0x7a, 0x92, 0x9c, 0xa4, 0xd0,
	0x08, 0xfa, 0x09, 0x6a, 0x7b, 0x68, 0x41, 0x41, 0xd6, 0x42, 0xa1, 0x97, 0x32, 0x26, 0x93, 0x64,
	0xc1, 0x64, 0x65, 0xb3, 0x46, 0xfa, 0xed, 0xcb, 0xee, 0x26, 0xf6, 0x94, 0xf7, 0x7e, 0xf3, 0x32,
	0x93, 0xcc, 0xc0, 0xa8, 0x3e, 0x63, 0x42, 0xf1, 0x59, 0x49, 0x2d, 0x59, 0xdf, 0x9a, 0x87, 0x49,
	0x26, 0x2a, 0xac, 0x3a, 0x1a, 0xbd, 0x43, 0xff, 0x95, 0x4e, 0x1a, 0xd9, 0x0c, 0x06, 0x32, 0xcb,
	0x6a, 0xd2, 0xa1, 0x37, 0xf7, 0x16, 0x3e, 0x6f, 0x9d, 0xe1, 0x8a, 0x4a, 0xd9, 0x50, 0xf8, 0xcf,
	0x71, 0xe7, 0xd8, 0x14, 0x7a, 0x98, 0xa6, 0x61, 0x6f, 0xee, 0x2d, 0xc6, 0xdc, 0xc8, 0x28, 0x06,
	0x7f, 0x47, 0x1a, 0x19, 0x03, 0xbf, 0xc2, 0x92, 0x6c, 0x9f, 0x80, 0x5b, 0x6d, 0x98, 0xfe, 0x39,
	0x93, 0x8d, 0x07, 0xdc, 0xea, 0xe8, 0x1b, 0x86, 0x7b, 0x45, 0x8d, 0xa0, 0xeb, 0xad, 0xec, 0xfd,
	0x95, 0x0d, 0x4b, 0x51, 0xa3, 0x1d, 0x3b, 0xe6, 0x56, 0xb3, 0x7b, 0xe8, 0x5f, 0x45, 0xaa, 0x0b,
	0xdb, 0x67, 0xc2, 0x9d, 0x31, 0x9f, 0x58, 0x90, 0xc8, 0x0b, 0x1d, 0xfa, 0x16, 0xb7, 0x2e, 0x5a,
	0x43, 0xef, 0x03, 0x73, 0xf3, 0x52, 0x83, 0xa7, 0x4b, 0xd7, 0xdd, 0x19, 0xf7, 0x5f, 0x58, 0xcb,
	0xca, 0x0e, 0x08, 0x78, 0xeb, 0xa2, 0x0c, 0x02, 0x4e, 0xb9, 0xa8, 0xb5, 0x42, 0xc5, 0x9e, 0xe0,
	0x7f, 0x49, 0x2a, 0x29, 0xb0, 0x72, 0x6b, 0x19, 0xad, 0xee, 0xe2, 0x6e, 0x7f, 0xbb, 0xb6, 0xc0,
	0x6f, 0x11, 0xf6, 0x08, 0xc3, 0x9a, 0x54, 0x23, 0x12, 0xb7, 0xac, 0xd1, 0x6a, 0x7a, 0x4b, 0x1f,
	0x1c, 0xe7, 0x5d, 0x60, 0xf3, 0x06, 0xb3, 0x44, 0x96, 0x31, 0x9e, 0x48, 0x17, 0x24, 0xf0, 0x8a,
	0x8a, 0x62, 0x7b, 0xa1, 0x0d, 0x1c, 0xcc, 0x63, 0x6f, 0xce, 0xf3, 0x15, 0xe5, 0x42, 0x17, 0x97,
	0x63, 0x9c, 0xc8, 0x72, 0xf9, 0xdc, 0x46, 0x3f, 0x51, 0xd1, 0x76, 0xfb, 0xb2, 0xb4, 0xe9, 0x5c,
	0x1e, 0x07, 0xf6, 0x92, 0xeb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x0d, 0x35, 0x37, 0xee,
	0x01, 0x00, 0x00,
}
